[package]
name = "gfaestus"
version = "0.1.0"
authors = ["christian <christian@chfi.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.20"
vulkano-shaders = "0.20"
vulkano-win = "0.20"
winit = "0.24"

crossbeam = "0.8"
parking_lot = "0.11.1"

image = "0.23"

rgb = "0.8.25"

nalgebra = "0.24"
nalgebra-glm = "0.10"

gfa = { version = "0.10" }
handlegraph = "0.7.0-alpha.2"

anyhow = "1.0"

rustc-hash = "1.1"